<?php
namespace ExcelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
	//Get the number of user wins
	public function getWinCount($winner) {
		$em = $this->getEntityManager();
		$dql = "SELECT COUNT(g) AS winCount
    				FROM \ExcelBundle\Entity\Game g
					WHERE g.winner = :winner
        			";
		$query = $em->createQuery($dql);
		$query->setParameters(array(
				'winner' => $winner
		));
		return $query->getSingleScalarResult();
	}

	//Get the number time player selected  a choice
	public function getChoiceCount($player,$choice) {
		$em = $this->getEntityManager();
		$dql = "SELECT COUNT(g) AS choiceCount
    				FROM \ExcelBundle\Entity\Game g
					WHERE g.".$player."Choice = :choice
        			";
		$query = $em->createQuery($dql);
		$query->setParameters(array(
				'choice' => $choice
		));
		return $query->getSingleScalarResult();
	}
}